[package]
name = "firecore-engine"
description = "Base engine for my games"
version = "0.0.3"
authors = ["Rhys H <donotdoughnut99@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/fiirecore/engine"
readme = "README.md"

[features]
default = []
audio = ["macroquad/audio"]

[dependencies]
macroquad = { version = "0.3", default-features = false }
enum-map = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
tinystr = { version = "0.4", features = ["serde"], default-features = false }
image = { version = "0.23.14", default-features = false, features = ["png", "tga"] }

firecore-text = { path = "crates/text" } # "0.0.1"
firecore-font-builder = { git = "https://github.com/DoNotDoughnut/firecore-font-builder", rev = "057373a", default-features = false }

async-trait = "0.1"

[dev-dependencies]
bincode = "1.3"

[workspace]
members = ["crates/*"]
default-members = ["crates/*"]
