[package]
name = "firecore-engine"
description = "Base engine for my games"
version = "0.0.2"
authors = ["Rhys H <donotdoughnut99@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/fiirecore/engine"
readme = "README.md"

[features]
default = []
audio = ["firecore-tetra/audio", "firecore-tetra/audio_vorbis", "dashmap"]

[dependencies]
firecore-tetra = { version = "0.0.1", default-features = false, features = [
    "serde_support",
    "texture_png",
    "sdl2_static_link",
    "sdl2_bundled",
] }
firecore-text = { path = "crates/text" } # "0.0.1"
firecore-audio = { path = "crates/audio" } #"0.0.1"
enum-map = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
hashbrown = "0.11"
dashmap = { version = "4", optional = true }

log = "0.4" # remove, handle audio errors in trait

[dev-dependencies]
bincode = "1.3"

[workspace]
members = ["crates/*"]
default-members = ["crates/*"]
