[package]
name = "firecore-engine"
description = "Base engine for my games"
version = "0.0.3"
authors = ["Rhys H <donotdoughnut99@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/fiirecore/engine"
readme = "README.md"

[features]
default = []
audio = ["macroquad/audio"]

[dependencies]
macroquad = { version = "0.3", default-features = false, features = ["log-rs", "backtrace"] }
firecore-text = { path = "crates/text" } # "0.0.1"
firecore-audio = { path = "crates/audio" } #"0.0.1"
enum-map = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
hashbrown = { version = "0.11", features = ["serde"] }
image = { version = "0.23.14", default-features = false, features = ["png", "tga"] }

async-trait = "0.1"

log = "0.4" # remove, handle audio errors in trait

[dev-dependencies]
bincode = "1.3"

[workspace]
members = ["crates/*"]
default-members = ["crates/*"]
