[package]
name = "firecore-engine"
version = "0.2.0"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

[features]
default = []
audio = ["tetra/audio", "tetra/audio_vorbis", "dashmap"]

[dependencies]
tetra = { git="https://github.com/DoNotDoughnut/tetra", branch="main", default-features=false, features=["serde_support", "texture_png", "sdl2_static_link", "sdl2_bundled"] }
firecore-text = { git="https://github.com/DoNotDoughnut/firecore-text" }
firecore-audio = { git="https://github.com/DoNotDoughnut/firecore-audio" }
enum-map = { version="1", features=["serde"] }
serde = { version="1", features=["derive"] }
hashbrown = "0.11"
dashmap = { version = "4", optional = true }

log = "0.4" # remove, handle audio errors in trait

[dev-dependencies]
bincode = "1.3"